export const SET_KEY = "SET_KEY";
export const SET_IS_MOBILE = "SET_IS_MOBILE";

export const SET_CATALOG = "SET_CATALOG";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const SET_IS_LOADING = "SET_IS_LOADING";

export const ADD_GAMES = "ADD_GAMES";

export const TOGGLE_NAME_SORT = "TOGGLE_NAME_SORT";
export const TOGGLE_RELEASE_SORT = "TOGGLE_RELEASE_SORT";

export const RESET_RELEASE_SORT = "RESET_RELEASE_SORT";
export const RESET_NAME_SORT = "RESET_NAME_SORT";

export const CHANGE_PLATFORM = "CHANGE_PLATFORM"
export const RESET_PLATFORMS = "RESET_PLATFORMS";
